### ISSUE TITLE
Lizard Mode Bug Analysis & Proposed Solutions

### ISSUE THREAD

**Issue by General4878** [ayufan/steam-deck-tools#215]
**I have released a version which emulates Lizard Mouse [on my fork](https://github.com/General4878/steam-deck-tools).**

---

# 🦎 Steam Deck Tools – Lizard Mode Bug Analysis & Proposed Solutions

I've been researching the known bug involving **Lizard Mouse** and **Lizard Buttons** on Steam Deck and wanted to share my findings and some potential solutions.

---

## 🔧 How Steam Deck Tools Works

- Steam Deck Tools (SDT) disables **Lizard Buttons** and emulates button presses in software.
- It keeps **Lizard Mouse enabled** to preserve smooth native mouse movement.
- This mismatch is the root of the issue.

---

## 🐞 Problem Description

The latest SteamOS firmware introduces a change:

> When **Lizard Buttons** and **Lizard Mouse** are not enabled or disabled together, it causes erratic behavior.

### In Desktop Mode:
- Mouse stutters every 250ms.
- SDT sends updates to the Neptune Device (Steam Controller) every 250ms.
- These updates disable Lizard Buttons and enable Lizard Mouse.
- This mismatch appears to cause a firmware reset, resulting in stutter.

### In Xbox360 Mode:
- The same mismatch causes firmware resets and inconsistent inputs.

### If both Lizard Mouse and Buttons are enabled:
- The firmware reset issue stops.
- But SDT still emulates button presses, causing **double inputs**.

### If both are disabled:
- The reset issue also stops.
- But we lose the **smooth movement** of Lizard Mouse—critical for many games.

---

### 1. Do Nothing and Wait _(least preferred)_
- This may be a low-priority bug in SteamOS.
- Valve might fix it in a future update, but there’s no guarantee.

### 2. Investigate New Reports to the Firmware
- The report format to the Neptune Device may have changed.
- Reverse engineering is needed to determine the correct bytes to send.
- This requires firmware expertise—any help is welcome!

### 3. Refine Steam Deck Tools Emulation
- **In Desktop Mode:**
  - Enable both Lizard Mouse and Buttons.
  - Remove button emulation in SDT to avoid double inputs.
- **In Xbox360 Mode:**
  - Disable both Lizard Mouse and Buttons.
  - Improve SDT’s mouse emulation to mimic Lizard Mouse:
    - Add haptic feedback
    - Match sensitivity
    - Implement glide behavior after release

> ⚠️ **Concerns:**
> - Could mouse emulation be flagged by anti-cheat systems? So far, it hasn’t.
> - Might it introduce input lag? Possibly—but it’s better than nothing.

---

### 🔧 Optimal Solution:
If anyone can reverse engineer the firmware to allow **Lizard Mouse enabled** and **Lizard Buttons disabled**—we need you!  
Gamers everywhere would be eternally grateful for saving **Windows on Deck**.

### 🛠️ A Nice Workaround:
I’m willing to improve SDT’s fallback **trackpad mouse emulation** to mimic Lizard Mouse in Xbox360 Mode.  
Time permitting, I’ll work on this soon. If you’re able to contribute, please do—every bit helps!

Thanks for reading! 🙂

**Comment by lyndon025** [comment]
Thanks for this write-up. im also experiencing the Lizard Mode Bug

**Comment by sergio151179** [comment]
But this bug is new, right? I don't remember this happening a few months ago. I've tried downgrading the BIOS, but the bug persists. Is there any way to roll back the Steam Deck so it works like it did before?

**Comment by mops1k** [comment]
> But this bug is new, right? I don't remember this happening a few months ago. I've tried downgrading the BIOS, but the bug persists. Is there any way to roll back the Steam Deck so it works like it did before?

Download my fork.

**Comment by ayufan** [comment]
You can change Lizard buttons configuration. This should help in some
circumstances.

**Comment by General4878** [comment]
I have already made a start to changing mouse emulation on SDT to match the behaviour of Lizard Mouse, and it works very similarly! Can’t even tell the difference.

All I need to do is add haptic feedback on trackpad drag and tidy the code up to optimise it, then I will request a push.

**Comment by ayufan** [comment]
A lot of problem was dual inputs. Maybe it is possible to connect to Steam and consume controller in SDT? I think there's a big chance that such controller would not be then used in Steam. Maybe something like this: https://github.com/Facepunch/Facepunch.Steamworks or https://github.com/rlabrecque/Steamworks.NET.

**Comment by General4878** [comment]
> A lot of problem was dual inputs. Maybe it is possible to connect to Steam and consume controller in SDT? I think there's a big chance that such controller would not be then used in Steam. Maybe something like this: https://github.com/Facepunch/Facepunch.Steamworks or https://github.com/rlabrecque/Steamworks.NET.

Double input is not the bug. 

From my understanding of the bug, dual inputs only occur when LizardButtons is enabled in x360 mode. The reason why this happens is because both the x360 input is registered AND the lizard button is registered, hence double input. 

Once LizardButtons is disabled (as it should be and how it is by default in SDT), double input stops.

The true bug is that when either LizardButtons or LizardMouse are not both enabled or disabled together every 250ms (as SDT does by default) the firmware seems to reset.

The only solution so far is to disable both LizardMouse and LizardButtons together, then SDT is fully usable except without the smooth mouse movements which sucks, and I’m trying to replicate.

**Comment by ayufan** [comment]
> The true bug is that when either LizardButtons or LizardMouse are not both enabled or disabled together every 250ms (as SDT does by default) the firmware seems to reset.

I don't understand. How firmware resets?

**Comment by General4878** [comment]
> > The true bug is that when either LizardButtons or LizardMouse are not both enabled or disabled together every 250ms (as SDT does by default) the firmware seems to reset.
> 
> I don't understand. How firmware resets?

 The SDT code sends a report to the Neptune device every 250ms to enable LizardMouse and disable LizardButtons.

This causes the trackpad and buttons to stop working for a few ms, then it works again. This repeats every 250ms as the call is made again.

This stops happening if we send a report to enable both LizardMouse and LizardButtons, or to disable LizardMouse and LizardButtons every 250ms.

So my best guess, is that the new firmware doesn’t like it when LizardMouse and LizardButtons are not both enabled or disabled at the same time.

**Comment by ayufan** [comment]
> So my best guess, is that the new firmware doesn’t like it when LizardMouse and LizardButtons are not both enabled or disabled at the same time.

That is interesting. It would help to see what Steam sends, as they do the same?

**Comment by General4878** [comment]
> > So my best guess, is that the new firmware doesn’t like it when LizardMouse and LizardButtons are not both enabled or disabled at the same time.
> 
> That is interesting. It would help to see what Steam sends, as they do the same?

It would be very interesting to see how Steam handles enabling/disabling Lizard, but I do not have the knowledge to reverse engineer this.

The likelihood is that Steam only ever enables LizardMouse and LizardButtons both together, not opposite like SDT which is why this has gone unnoticed by Valve.

Anyway, I’m working on creating a programmatic replication of LizardMouse smooth movement, so SDT doesn’t need to have LizardMouse enabled to have the smooth glide.

**Comment by ayufan** [comment]
> Anyway, I’m working on creating a programmatic replication of LizardMouse smooth movement, so SDT doesn’t need to have LizardMouse enabled to have the smooth glide.

Nice. Looking forward to it :)

**Comment by ayufan** [comment]
@General4878 

This ping is sent to disable Valve controller Mouse and Keyboard emulation. https://github.com/ayufan/steam-deck-tools/blob/main/SteamController/Devices/SteamControllerLizard.cs#L19. So, this would mean that controller expects both, not one. So, we would have to either enable both Lizards or none, but cannot enable or another.

Those are meaning of those magic numbers: https://github.com/torvalds/linux/blob/master/drivers/hid/hid-steam.c#L86

**Comment by ayufan** [comment]
@General4878 This is super interesting: https://github.com/torvalds/linux/blob/master/drivers/hid/hid-steam.c#L86. It seems that this might be the answer for lizard mode.  Especially the: SETTING_STEAM_WATCHDOG_ENABLE.

**Comment by General4878** [comment]
> [@General4878](https://github.com/General4878) This is super interesting: https://github.com/torvalds/linux/blob/master/drivers/hid/hid-steam.c#L86. It seems that this might be the answer for lizard mode. Especially the: SETTING_STEAM_WATCHDOG_ENABLE.

Oh, this is interesting… maybe sending this report stops the reset. I’ll give it a shot

**Comment by ayufan** [comment]
Trying to make changes. Will send a change soon.

**Comment by General4878** [comment]
[0x87, 0x03, 0x46, 0x00, 0x00]
I think these would be the bytes that need to be sent?

**Comment by General4878** [comment]
Hi @ayufan,

I've implemented a faux Lizard Mouse emulation that allows smooth mouse movement and haptic feedback even when Lizard Mouse is disabled. This helps retain the fluid motion experience while avoiding the stuttering bug caused by Lizard Mouse and Lizard Buttons being enabled simultaneously.

The method—`MoveByFauxLizard`—mimics the original behavior without relying on the Lizard Mouse state machine. It’s modular and works well in isolation.

I’d love to contribute this to the repo, but I don’t currently have permission to push a branch. Would you be open to reviewing it if I submit a patch or fork?

**Comment by ayufan** [comment]
@General4878 Open PR from Fork.

**Comment by gamees-31** [comment]
I still don't understand if there is a solution to make everything work as before?

**Comment by General4878** [comment]
> I still don't understand if there is a solution to make everything work as before?

If you want lizard mouse as before, go to my fork and open faux-lizard-mouse branch. Download the branch, extract it and run build.cmd in the scripts folder and put the build on your Steam Deck. You can then enable faux lizard mouse in controller settings and you’ll get smooth mouse movements again.

**Comment by gamees-31** [comment]
> > Я до сих пор не понимаю, можно ли как-то вернуть всё на круги своя?
> 
> Если вы хотите, чтобы мышь работала как раньше, перейдите в мой форк и откройте ветку faux-lizard-mouse. Скачайте ветку, распакуйте ее, запустите build.cmd в папке со скриптами и установите сборку на Steam Deck. Затем включите faux lizard Mouse в настройках контроллера, и движения мыши снова станут плавными.

Bro, I'm sorry, I don't know much about all this, could you tell me what I did wrong? I downloaded your fork in the scripts folder and launched build.bat, then build_installer.bat, did I do the right thing?

**Comment by General4878** [comment]
> > > Я до сих пор не понимаю, можно ли как-то вернуть всё на круги своя?
> > 
> > 
> > Если вы хотите, чтобы мышь работала как раньше, перейдите в мой форк и откройте ветку faux-lizard-mouse. Скачайте ветку, распакуйте ее, запустите build.cmd в папке со скриптами и установите сборку на Steam Deck. Затем включите faux lizard Mouse в настройках контроллера, и движения мыши снова станут плавными.
> 
> Bro, I'm sorry, I don't know much about all this, could you tell me what I did wrong? I downloaded your fork in the scripts folder and launched build.bat, then build_installer.bat, did I do the right thing?

All you need to do is run build.bat (right click as administratior) and a new folder in the root directory should appear that I think is called build-Release or something like that. You copy that to your steam deck and place it somewhere like C:/, and you don’t need to install anything, just double click the exes in the folder. I could look at building it myself and publishing it in my repository but I need to find the time to set this up.

**Comment by General4878** [comment]
> > > Я до сих пор не понимаю, можно ли как-то вернуть всё на круги своя?
> > 
> > 
> > Если вы хотите, чтобы мышь работала как раньше, перейдите в мой форк и откройте ветку faux-lizard-mouse. Скачайте ветку, распакуйте ее, запустите build.cmd в папке со скриптами и установите сборку на Steam Deck. Затем включите faux lizard Mouse в настройках контроллера, и движения мыши снова станут плавными.
> 
> Bro, I'm sorry, I don't know much about all this, could you tell me what I did wrong? I downloaded your fork in the scripts folder and launched build.bat, then build_installer.bat, did I do the right thing?

And don’t forget, once you successfully build it and copy it to your steam deck, you need to enable Faux Lizard Mouse in the controller settings to get smooth lizard movement

**Comment by gamees-31** [comment]
> > > > Я до сих пор не понимаю, можно ли как-то вернуть всё на круги своя?
> > > 
> > > 
> > > Если вы хотите, чтобы мышь работала как раньше, перейдите в мой форк и откройте ветку faux-lizard-mouse. Скачайте ветку, распакуйте ее, запустите build.cmd в папке со скриптами и установите сборку на Steam Deck. Затем включите faux lizard Mouse в настройках контроллера, и движения мыши снова станут плавными.
> > 
> > 
> > Bro, I'm sorry, I don't know much about all this, could you tell me what I did wrong? I downloaded your fork in the scripts folder and launched build.bat, then build_installer.bat, did I do the right thing?
> 
> And don’t forget, once you successfully build it and copy it to your steam deck, you need to enable Faux Lizard Mouse in the controller settings to get smooth lizard movement

Thanks buddy, you're the best.  Everything works like a Swiss watch

**Comment by General4878** [comment]
I have now published Lizard Mouse emulation [on my fork](https://github.com/General4878/steam-deck-tools) if you wish to download it without needing to build it.
