### ISSUE TITLE
Flakey Steam Button Detection

### ISSUE THREAD

**Issue by cgarst** [ayufan/steam-deck-tools#28]
The controller app seems to have trouble registering the steam button. It works about 10% of the time for me. Conversely, SWICD or Steam detect it reliably, so it seems specific to this implementation. Is it just me?

The default expectation (outside of Steam) is to use it to trigger the Xbox game bar overlay, or as the Xbox button within the Xbox app's remote play and cloud streaming.

**Comment by ayufan** [comment]
@cgarst I believe you are first. I never saw anything with that. If you hover over Steam Controller icon what rate of updates it shows?

**Comment by cgarst** [comment]
That's interesting. Rate of updates appears to be 250-252/s. All other buttons behave normally. I'll keep experimenting.

Some other context in case someone else finds the same:
BIOS version F7A0105
Windows 11 Pro Version 22H2
Just installed over latest SteamOS last week

**Comment by ayufan** [comment]
Hmm. I might know what is happening.

The STEAM button is special purpose button that if pressed it's stroke is registered only for a single frame of controller report. This in some cases might result in action not being received.

Can you compile the app, because if yes, you could try a small "fix" whether this works for you.

**Comment by ayufan** [comment]
@cgarst OK. Lets try this. In about 5 mins here at the bottom there will be artifact with latest build: https://github.com/ayufan/steam-deck-tools/actions/runs/3721619525/jobs/6311895228.

**Comment by ayufan** [comment]
@cgarst The potential fix was released as part of 0.5.42.

**Comment by cgarst** [comment]
@ayufan thank you. Testing 0.5.42 and still seeing some misses though it's definitely an improved rate of success. 

Test case:
- Have Xbox game bar enabled
- Every second, press STEAM button for 20 seconds
- Note success or failure of button toggling game bar

Test result:
- 18 passes, 2 failures

Was seeing about 10% success before, so at 90% the improvement is great. The remaining 10% could also be the gamebar being unresponsive. I'll run with this for a while and report some more detailed test results if it still seems wonky in real scenarios.

**Comment by ayufan** [comment]
I wonder what is usual minimal hold rate of button. It probably this is
needed to be tuned :)

**Comment by cgarst** [comment]
@ayufan I'd say that this is still an issue, though it's difficult to quantify. Sometimes it will work 1/10 times, other times it will work 10/10.

**Comment by ayufan** [comment]
Hopefully improved in 0.5.48

Ref.:
- https://github.com/ayufan/steam-deck-tools/commit/4c870c1b98d665083e7ebf63e1896cbd26bfa6f2
- https://github.com/ayufan/steam-deck-tools/releases/tag/0.5.48
